create_ticker:
  name: Create Universal Controller Ticker
  description: Create a new Universal Controller ticker with default settings
  fields:
    ticker_id:
      name: Ticker ID
      description: Unique identifier for this ticker instance
      required: true
      selector:
        text:
    name:
      name: Ticker Name
      description: Human-readable name for this ticker
      required: true
      selector:
        text:

update_ticker:
  name: Update Universal Controller Ticker
  description: Update ticker configuration (use the card UI for detailed editing)
  fields:
    ticker_id:
      name: Ticker ID
      description: Unique identifier for the ticker to update
      required: true
      selector:
        text:
    enabled:
      name: Enabled
      description: Whether this ticker should run automatically
      required: false
      selector:
        boolean:

delete_ticker:
  name: Delete Universal Controller Ticker
  description: Delete a ticker instance
  fields:
    ticker_id:
      name: Ticker ID
      description: Unique identifier for the ticker to delete
      required: true
      selector:
        text:

get_ticker:
  name: Get Universal Controller Ticker
  description: Get configuration and status for a specific ticker
  fields:
    ticker_id:
      name: Ticker ID
      description: Unique identifier for the ticker
      required: true
      selector:
        text:

list_tickers:
  name: List Universal Controller Tickers
  description: Get all ticker configurations and their current status
  fields: {}

execute_ticker:
  name: Execute Universal Controller Ticker
  description: Manually execute a ticker's code immediately
  fields:
    ticker_id:
      name: Ticker ID
      description: Unique identifier for the ticker to execute
      required: true
      selector:
        text:

save_config:
  name: Save Configuration (Legacy)
  description: "[DEPRECATED] Use create_ticker or update_ticker instead"
  fields:
    card_id:
      name: Card ID
      description: Unique identifier for the card
      required: true
      selector:
        text:
    user_code:
      name: User Code
      description: TypeScript/JavaScript code to execute
      required: false
      selector:
        text:
          multiline: true
    html_template:
      name: HTML Template
      description: HTML template with placeholder variables
      required: false
      selector:
        text:
          multiline: true
    css_styles:
      name: CSS Styles
      description: CSS styles for the rendered content
      required: false
      selector:
        text:
          multiline: true

load_config:
  name: Load Configuration (Legacy)
  description: "[DEPRECATED] Use get_ticker instead"
  fields:
    card_id:
      name: Card ID
      description: Unique identifier for the card
      required: true
      selector:
        text:

get_all_configs:
  name: Get All Configurations (Legacy)
  description: "[DEPRECATED] Use list_tickers instead"
  fields: {}

register_frontend:
  name: Register Frontend
  description: Manually register the Universal Controller frontend (useful after updates)
  fields: {}